#include "inputs.h"
#include "Pins.h"

// ENABLE INPUT-PULLDOWN
// Set Pint as GPIO
// Enable Interrupt on both falling and rising edge
#define DIGITALINPUT PORT_PCR_PE | PORT_PCR_MUX(1) | PORT_PCR_IRQC(11)

#define ANALOGINPUT PORT_PCR_MUX(1)


void initInputs (void)
{

    BTN_BK_UP_CONFIG = DIGITALINPUT;
    BTN_BK_DWN_CONFIG = DIGITALINPUT;
    BTN_MODE_CONFIG = DIGITALINPUT;
    BTN_SAVE_CONFIG = DIGITALINPUT;
    BTN_BACK_CONFIG = DIGITALINPUT;
    BTN_SELECT_CONFIG = DIGITALINPUT;

    ENCODER_CLK_CONFIG = DIGITALINPUT;
    ENCODER_DT_CONFIG = DIGITALINPUT;

    PEDAL_CONFIG = ANALOGINPUT;

    TRACK1_PLAY_CONFIG = DIGITALINPUT;
    TRACK1_OVD_CONFIG = DIGITALINPUT;
    TRACK2_PLAY_CONFIG = DIGITALINPUT;
    TRACK2_OVD_CONFIG = DIGITALINPUT;
    TRACK3_PLAY_CONFIG = DIGITALINPUT;
    TRACK3_OVD_CONFIG = DIGITALINPUT;
    TRACK4_PLAY_CONFIG = DIGITALINPUT;
    TRACK4_OVD_CONFIG = DIGITALINPUT;
    TRACK5_PLAY_CONFIG = DIGITALINPUT;
    TRACK5_OVD_CONFIG = DIGITALINPUT;

    CSTM_SW1_CONFIG = DIGITALINPUT;
    CSTM_SW2_CONFIG = DIGITALINPUT;
    CSTM_SW3_CONFIG = DIGITALINPUT;
    CSTM_SW4_CONFIG = DIGITALINPUT;
    CSTM_SW5_CONFIG = DIGITALINPUT;
}

void PORTA_IQRHandler(void)
{
    PORTA_ISFR = 1;
    
    static uint32_t lastState = 0;
    uint32_t change = GPIOA_PDIR ^ lastState;

    switch (change){

        case TRACK4_PLAY_PINMASK:
        
    }
    
}